USE [master]
GO

/****** Object:  Database [QuanLyNhanvien]    Script Date: 23/04/2022 9:54:44 SA ******/
CREATE DATABASE [QuanLyNhanvien]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'quanlynhanvien_data', FILENAME = N'D:\TH_Java\quanlynhanvien_data.mdf' , SIZE = 10240KB , MAXSIZE = 20480KB , FILEGROWTH = 20%)
 LOG ON 
( NAME = N'quanlynhanvien_log', FILENAME = N'D:\TH_Java\quanlynhanvien_log.ldf' , SIZE = 10240KB , MAXSIZE = 20480KB , FILEGROWTH = 20%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QuanLyNhanvien].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [QuanLyNhanvien] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [QuanLyNhanvien] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [QuanLyNhanvien] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [QuanLyNhanvien] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [QuanLyNhanvien] SET ARITHABORT OFF 
GO

ALTER DATABASE [QuanLyNhanvien] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [QuanLyNhanvien] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [QuanLyNhanvien] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [QuanLyNhanvien] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [QuanLyNhanvien] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [QuanLyNhanvien] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [QuanLyNhanvien] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [QuanLyNhanvien] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [QuanLyNhanvien] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [QuanLyNhanvien] SET  ENABLE_BROKER 
GO

ALTER DATABASE [QuanLyNhanvien] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [QuanLyNhanvien] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [QuanLyNhanvien] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [QuanLyNhanvien] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [QuanLyNhanvien] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [QuanLyNhanvien] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [QuanLyNhanvien] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [QuanLyNhanvien] SET RECOVERY FULL 
GO

ALTER DATABASE [QuanLyNhanvien] SET  MULTI_USER 
GO

ALTER DATABASE [QuanLyNhanvien] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [QuanLyNhanvien] SET DB_CHAINING OFF 
GO

ALTER DATABASE [QuanLyNhanvien] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [QuanLyNhanvien] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [QuanLyNhanvien] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [QuanLyNhanvien] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [QuanLyNhanvien] SET QUERY_STORE = OFF
GO

ALTER DATABASE [QuanLyNhanvien] SET  READ_WRITE 
GO

